# Generated by Django 6.0.7 on 2026-08-04 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Gateway-issued payment ID (e.g. Razorpay pay_xxx).', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, help_text='Gateway-issued refund ID after a refund is processed.', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'),
        ),
    ]
