# Generated by Django 6.0.7 on 2026-08-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_id_payment_refund_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Gateway-issued payment ID (e.g. Razorpay pay_xxx).', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, help_text='Gateway-issued refund ID after a refund is processed.', max_length=100, null=True, unique=True),
        ),
    ]
