from datetime import date, time, timedelta

DEMO_FLIGHTS = [
    {
        'airline_name': 'SkyWay Airlines',
        'flight_number': 'SW101',
        'departure_airport': 'JFK',
        'arrival_airport': 'LAX',
        'departure_city': 'New York',
        'destination_city': 'Los Angeles',
        'departure_date': date.today() + timedelta(days=1),
        'departure_time': time(8, 30),
        'arrival_date': date.today() + timedelta(days=1),
        'arrival_time': time(11, 45),
        'flight_duration': '6h 15m',
        'flight_type': 'one_way',
        'cabin_class': 'Economy',
        'available_seats': 45,
        'price': 299.00,
        'discount_percentage': 15,
        'discounted_price': 254.15,
        'refundable': True,
    },
    {
        'airline_name': 'Global Air',
        'flight_number': 'GA205',
        'departure_airport': 'ORD',
        'arrival_airport': 'LHR',
        'departure_city': 'Chicago',
        'destination_city': 'London',
        'departure_date': date.today() + timedelta(days=2),
        'departure_time': time(21, 0),
        'arrival_date': date.today() + timedelta(days=3),
        'arrival_time': time(10, 30),
        'flight_duration': '7h 30m',
        'flight_type': 'one_way',
        'cabin_class': 'Economy',
        'available_seats': 120,
        'price': 549.00,
        'discount_percentage': 0,
        'discounted_price': 549.00,
        'refundable': False,
    },
    {
        'airline_name': 'Pacific Star',
        'flight_number': 'PS310',
        'departure_airport': 'SFO',
        'arrival_airport': 'NRT',
        'departure_city': 'San Francisco',
        'destination_city': 'Tokyo',
        'departure_date': date.today() + timedelta(days=5),
        'departure_time': time(11, 0),
        'arrival_date': date.today() + timedelta(days=6),
        'arrival_time': time(14, 30),
        'flight_duration': '11h 30m',
        'flight_type': 'one_way',
        'cabin_class': 'Economy',
        'available_seats': 80,
        'price': 699.00,
        'discount_percentage': 25,
        'discounted_price': 524.25,
        'refundable': True,
    },
    {
        'airline_name': 'EuroWings',
        'flight_number': 'EW450',
        'departure_airport': 'CDG',
        'arrival_airport': 'FCO',
        'departure_city': 'Paris',
        'destination_city': 'Rome',
        'departure_date': date.today() + timedelta(days=2),
        'departure_time': time(7, 45),
        'arrival_date': date.today() + timedelta(days=2),
        'arrival_time': time(9, 30),
        'flight_duration': '1h 45m',
        'flight_type': 'one_way',
        'cabin_class': 'Economy',
        'available_seats': 35,
        'price': 129.00,
        'discount_percentage': 0,
        'discounted_price': 129.00,
        'refundable': False,
    },
    {
        'airline_name': 'Desert Wings',
        'flight_number': 'DW800',
        'departure_airport': 'DXB',
        'arrival_airport': 'SYD',
        'departure_city': 'Dubai',
        'destination_city': 'Sydney',
        'departure_date': date.today() + timedelta(days=7),
        'departure_time': time(2, 0),
        'arrival_date': date.today() + timedelta(days=8),
        'arrival_time': time(17, 0),
        'flight_duration': '14h 0m',
        'flight_type': 'one_way',
        'cabin_class': 'Economy',
        'available_seats': 150,
        'price': 899.00,
        'discount_percentage': 10,
        'discounted_price': 809.10,
        'refundable': True,
    },
    {
        'airline_name': 'Coastal Express',
        'flight_number': 'CE150',
        'departure_airport': 'MIA',
        'arrival_airport': 'BOG',
        'departure_city': 'Miami',
        'destination_city': 'Bogota',
        'departure_date': date.today() + timedelta(days=3),
        'departure_time': time(9, 0),
        'arrival_date': date.today() + timedelta(days=3),
        'arrival_time': time(12, 30),
        'flight_duration': '4h 30m',
        'flight_type': 'one_way',
        'cabin_class': 'Economy',
        'available_seats': 60,
        'price': 199.00,
        'discount_percentage': 30,
        'discounted_price': 139.30,
        'refundable': False,
    },
]