from datetime import time, timedelta

from django.core.management.base import BaseCommand
from django.utils import timezone

from flights.models import Flight


class Command(BaseCommand):
    help = 'Seed the database with sample flight data'

    def handle(self, *args, **kwargs):
        flights_data = [
            {
                'airline_name': 'SkyWay Airlines',
                'flight_number': 'SW101',
                'departure_airport': 'JFK',
                'arrival_airport': 'LAX',
                'departure_city': 'New York',
                'destination_city': 'Los Angeles',
                'departure_date': timezone.now().date() + timedelta(days=1),
                'departure_time': time(8, 30),
                'arrival_date': timezone.now().date() + timedelta(days=1),
                'arrival_time': time(11, 45),
                'flight_duration': timedelta(hours=6, minutes=15),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 200,
                'available_seats': 45,
                'price': 299.00,
                'discount_percentage': 15,
                'baggage_allowance': '1 checked bag (23kg)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Comfortable non-stop flight from New York to Los Angeles with complimentary meals and entertainment.',
            },
            {
                'airline_name': 'SkyWay Airlines',
                'flight_number': 'SW102',
                'departure_airport': 'JFK',
                'arrival_airport': 'LAX',
                'departure_city': 'New York',
                'destination_city': 'Los Angeles',
                'departure_date': timezone.now().date() + timedelta(days=1),
                'departure_time': time(14, 15),
                'arrival_date': timezone.now().date() + timedelta(days=1),
                'arrival_time': time(17, 30),
                'flight_duration': timedelta(hours=6, minutes=15),
                'flight_type': 'one_way',
                'cabin_class': 'business',
                'total_seats': 40,
                'available_seats': 12,
                'price': 899.00,
                'discount_percentage': 10,
                'baggage_allowance': '2 checked bags (32kg each)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Premium business class experience with lie-flat seats and gourmet dining.',
            },
            {
                'airline_name': 'Global Air',
                'flight_number': 'GA205',
                'departure_airport': 'ORD',
                'arrival_airport': 'LHR',
                'departure_city': 'Chicago',
                'destination_city': 'London',
                'departure_date': timezone.now().date() + timedelta(days=2),
                'departure_time': time(21, 00),
                'arrival_date': timezone.now().date() + timedelta(days=3),
                'arrival_time': time(10, 30),
                'flight_duration': timedelta(hours=7, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 280,
                'available_seats': 120,
                'price': 549.00,
                'discount_percentage': 0,
                'baggage_allowance': '1 checked bag (23kg)',
                'refundable': False,
                'status': 'scheduled',
                'description': 'Overnight flight to London Heathrow with in-flight entertainment and meal service.',
            },
            {
                'airline_name': 'Global Air',
                'flight_number': 'GA206',
                'departure_airport': 'ORD',
                'arrival_airport': 'LHR',
                'departure_city': 'Chicago',
                'destination_city': 'London',
                'departure_date': timezone.now().date() + timedelta(days=2),
                'departure_time': time(22, 30),
                'arrival_date': timezone.now().date() + timedelta(days=3),
                'arrival_time': time(12, 00),
                'flight_duration': timedelta(hours=7, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'premium_economy',
                'total_seats': 60,
                'available_seats': 25,
                'price': 799.00,
                'discount_percentage': 20,
                'baggage_allowance': '2 checked bags (23kg each)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Premium economy with extra legroom, priority boarding, and upgraded meals.',
            },
            {
                'airline_name': 'Pacific Star',
                'flight_number': 'PS310',
                'departure_airport': 'SFO',
                'arrival_airport': 'NRT',
                'departure_city': 'San Francisco',
                'destination_city': 'Tokyo',
                'departure_date': timezone.now().date() + timedelta(days=5),
                'departure_time': time(11, 00),
                'arrival_date': timezone.now().date() + timedelta(days=6),
                'arrival_time': time(14, 30),
                'flight_duration': timedelta(hours=11, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 250,
                'available_seats': 80,
                'price': 699.00,
                'discount_percentage': 25,
                'baggage_allowance': '2 checked bags (23kg each)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Direct flight to Tokyo Narita with Japanese cuisine and entertainment options.',
            },
            {
                'airline_name': 'Pacific Star',
                'flight_number': 'PS311',
                'departure_airport': 'SFO',
                'arrival_airport': 'NRT',
                'departure_city': 'San Francisco',
                'destination_city': 'Tokyo',
                'departure_date': timezone.now().date() + timedelta(days=5),
                'departure_time': time(13, 00),
                'arrival_date': timezone.now().date() + timedelta(days=6),
                'arrival_time': time(16, 30),
                'flight_duration': timedelta(hours=11, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'first',
                'total_seats': 16,
                'available_seats': 4,
                'price': 3499.00,
                'discount_percentage': 0,
                'baggage_allowance': '3 checked bags (32kg each)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Ultimate luxury first class with private suites, caviar service, and champagne.',
            },
            {
                'airline_name': 'Coastal Express',
                'flight_number': 'CE150',
                'departure_airport': 'MIA',
                'arrival_airport': 'BOG',
                'departure_city': 'Miami',
                'destination_city': 'Bogota',
                'departure_date': timezone.now().date() + timedelta(days=3),
                'departure_time': time(9, 00),
                'arrival_date': timezone.now().date() + timedelta(days=3),
                'arrival_time': time(12, 30),
                'flight_duration': timedelta(hours=4, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 180,
                'available_seats': 60,
                'price': 199.00,
                'discount_percentage': 30,
                'baggage_allowance': '1 checked bag (23kg)',
                'refundable': False,
                'status': 'scheduled',
                'description': 'Quick flight to Bogota with light refreshments served.',
            },
            {
                'airline_name': 'EuroWings',
                'flight_number': 'EW450',
                'departure_airport': 'CDG',
                'arrival_airport': 'FCO',
                'departure_city': 'Paris',
                'destination_city': 'Rome',
                'departure_date': timezone.now().date() + timedelta(days=2),
                'departure_time': time(7, 45),
                'arrival_date': timezone.now().date() + timedelta(days=2),
                'arrival_time': time(9, 30),
                'flight_duration': timedelta(hours=1, minutes=45),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 150,
                'available_seats': 35,
                'price': 129.00,
                'discount_percentage': 0,
                'baggage_allowance': '1 cabin bag only',
                'refundable': False,
                'status': 'scheduled',
                'description': 'Short and sweet hop from Paris to Rome.',
            },
            {
                'airline_name': 'EuroWings',
                'flight_number': 'EW451',
                'departure_airport': 'CDG',
                'arrival_airport': 'FCO',
                'departure_city': 'Paris',
                'destination_city': 'Rome',
                'departure_date': timezone.now().date() + timedelta(days=2),
                'departure_time': time(18, 00),
                'arrival_date': timezone.now().date() + timedelta(days=2),
                'arrival_time': time(19, 45),
                'flight_duration': timedelta(hours=1, minutes=45),
                'flight_type': 'one_way',
                'cabin_class': 'business',
                'total_seats': 24,
                'available_seats': 8,
                'price': 349.00,
                'discount_percentage': 5,
                'baggage_allowance': '2 checked bags (23kg each)',
                'refundable': True,
                'status': 'delayed',
                'description': 'Evening business class service with fine wine and hot meals.',
            },
            {
                'airline_name': 'Desert Wings',
                'flight_number': 'DW800',
                'departure_airport': 'DXB',
                'arrival_airport': 'SYD',
                'departure_city': 'Dubai',
                'destination_city': 'Sydney',
                'departure_date': timezone.now().date() + timedelta(days=7),
                'departure_time': time(2, 00),
                'arrival_date': timezone.now().date() + timedelta(days=8),
                'arrival_time': time(17, 00),
                'flight_duration': timedelta(hours=14, minutes=00),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 300,
                'available_seats': 150,
                'price': 899.00,
                'discount_percentage': 10,
                'baggage_allowance': '2 checked bags (23kg each)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Long-haul flight to Sydney with multiple meal services and entertainment system.',
            },
            {
                'airline_name': 'Desert Wings',
                'flight_number': 'DW801',
                'departure_airport': 'DXB',
                'arrival_airport': 'SYD',
                'departure_city': 'Dubai',
                'destination_city': 'Sydney',
                'departure_date': timezone.now().date() + timedelta(days=7),
                'departure_time': time(3, 00),
                'arrival_date': timezone.now().date() + timedelta(days=8),
                'arrival_time': time(18, 00),
                'flight_duration': timedelta(hours=14, minutes=00),
                'flight_type': 'one_way',
                'cabin_class': 'business',
                'total_seats': 48,
                'available_seats': 20,
                'price': 2499.00,
                'discount_percentage': 0,
                'baggage_allowance': '2 checked bags (32kg each)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Award-winning business class with fully flat beds and à la carte dining.',
            },
            {
                'airline_name': 'Nordic Air',
                'flight_number': 'NA220',
                'departure_airport': 'ARN',
                'arrival_airport': 'REK',
                'departure_city': 'Stockholm',
                'destination_city': 'Reykjavik',
                'departure_date': timezone.now().date() + timedelta(days=4),
                'departure_time': time(15, 30),
                'arrival_date': timezone.now().date() + timedelta(days=4),
                'arrival_time': time(17, 00),
                'flight_duration': timedelta(hours=3, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 120,
                'available_seats': 90,
                'price': 159.00,
                'discount_percentage': 20,
                'baggage_allowance': '1 checked bag (23kg)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Scenic flight over the North Atlantic to Iceland.',
            },
            {
                'airline_name': 'Maple Air',
                'flight_number': 'MA500',
                'departure_airport': 'YYZ',
                'arrival_airport': 'LGA',
                'departure_city': 'Toronto',
                'destination_city': 'New York',
                'departure_date': timezone.now().date() + timedelta(days=1),
                'departure_time': time(6, 00),
                'arrival_date': timezone.now().date() + timedelta(days=1),
                'arrival_time': time(7, 30),
                'flight_duration': timedelta(hours=1, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 100,
                'available_seats': 25,
                'price': 179.00,
                'discount_percentage': 0,
                'baggage_allowance': '1 cabin bag + 1 checked bag',
                'refundable': False,
                'status': 'cancelled',
                'description': 'Early morning shuttle to New York LaGuardia.',
            },
            {
                'airline_name': 'Maple Air',
                'flight_number': 'MA501',
                'departure_airport': 'YYZ',
                'arrival_airport': 'LGA',
                'departure_city': 'Toronto',
                'destination_city': 'New York',
                'departure_date': timezone.now().date() + timedelta(days=1),
                'departure_time': time(16, 00),
                'arrival_date': timezone.now().date() + timedelta(days=1),
                'arrival_time': time(17, 30),
                'flight_duration': timedelta(hours=1, minutes=30),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 100,
                'available_seats': 55,
                'price': 199.00,
                'discount_percentage': 10,
                'baggage_allowance': '1 cabin bag + 1 checked bag',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Afternoon shuttle service between Toronto and New York.',
            },
            {
                'airline_name': 'SunJet',
                'flight_number': 'SJ900',
                'departure_airport': 'MCO',
                'arrival_airport': 'CUN',
                'departure_city': 'Orlando',
                'destination_city': 'Cancun',
                'departure_date': timezone.now().date() + timedelta(days=6),
                'departure_time': time(10, 30),
                'arrival_date': timezone.now().date() + timedelta(days=6),
                'arrival_time': time(12, 45),
                'flight_duration': timedelta(hours=2, minutes=15),
                'flight_type': 'one_way',
                'cabin_class': 'economy',
                'total_seats': 160,
                'available_seats': 95,
                'price': 249.00,
                'discount_percentage': 0,
                'baggage_allowance': '1 checked bag (23kg)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Tropical getaway flight to Cancun with complimentary drinks.',
            },
            {
                'airline_name': 'SunJet',
                'flight_number': 'SJ901',
                'departure_airport': 'MCO',
                'arrival_airport': 'CUN',
                'departure_city': 'Orlando',
                'destination_city': 'Cancun',
                'departure_date': timezone.now().date() + timedelta(days=6),
                'departure_time': time(14, 00),
                'arrival_date': timezone.now().date() + timedelta(days=6),
                'arrival_time': time(16, 15),
                'flight_duration': timedelta(hours=2, minutes=15),
                'flight_type': 'one_way',
                'cabin_class': 'premium_economy',
                'total_seats': 40,
                'available_seats': 18,
                'price': 399.00,
                'discount_percentage': 15,
                'baggage_allowance': '2 checked bags (23kg each)',
                'refundable': True,
                'status': 'scheduled',
                'description': 'Premium economy to Cancun with extra legroom and priority service.',
            },
        ]

        count = 0
        for data in flights_data:
            Flight.objects.get_or_create(
                flight_number=data['flight_number'],
                defaults=data
            )
            count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {count} flights'))
