# Generated by Django 6.0.7 on 2026-07-29 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('destination', models.CharField(db_index=True, max_length=200)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_nights', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('Adventure', 'Adventure'), ('Family', 'Family'), ('Honeymoon', 'Honeymoon'), ('Luxury', 'Luxury'), ('Solo', 'Solo'), ('Group', 'Group'), ('Wildlife', 'Wildlife'), ('Beach', 'Beach'), ('Hill Station', 'Hill Station')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('max_travelers', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('best_travel_season', models.CharField(blank=True, max_length=200)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-average_rating', 'title'],
                'indexes': [models.Index(fields=['destination', 'country'], name='packages_tr_destina_e7e6e8_idx'), models.Index(fields=['category'], name='packages_tr_categor_e9bfc1_idx'), models.Index(fields=['price'], name='packages_tr_price_27c401_idx'), models.Index(fields=['active', 'featured'], name='packages_tr_active_24d690_idx'), models.Index(fields=['duration_days'], name='packages_tr_duratio_4a3219_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
