# Generated by Django 6.0.7 on 2026-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Family', 'Family'), ('Honeymoon', 'Honeymoon'), ('Luxury', 'Luxury'), ('Solo', 'Solo'), ('Group', 'Group'), ('Wildlife', 'Wildlife'), ('Beach', 'Beach'), ('Hill Station', 'Hill Station'), ('Wellness', 'Wellness')], db_index=True, max_length=30),
        ),
    ]
