# Generated by Django 6.0.7 on 2026-07-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_travelpackage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
