# Generated by Django 6.0.7 on 2026-07-29 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('star_rating', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('wifi', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-average_rating', 'name'],
                'indexes': [models.Index(fields=['city', 'country'], name='hotels_hote_city_a01868_idx'), models.Index(fields=['star_rating'], name='hotels_hote_star_ra_e9d0d2_idx'), models.Index(fields=['price_per_night'], name='hotels_hote_price_p_7002d9_idx'), models.Index(fields=['active', 'featured'], name='hotels_hote_active_9411cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
