# Generated by Django 6.0.7 on 2026-07-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
