# Generated by Django 6.0.7 on 2026-07-29 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=200)),
                ('airline_logo', models.ImageField(blank=True, null=True, upload_to='airlines/')),
                ('flight_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('departure_airport', models.CharField(max_length=200)),
                ('arrival_airport', models.CharField(max_length=200)),
                ('departure_city', models.CharField(db_index=True, max_length=100)),
                ('destination_city', models.CharField(db_index=True, max_length=100)),
                ('departure_date', models.DateField(db_index=True)),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('flight_duration', models.DurationField()),
                ('flight_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('cabin_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20)),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('baggage_allowance', models.CharField(blank=True, max_length=200)),
                ('refundable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-departure_date', 'departure_time'],
                'indexes': [models.Index(fields=['departure_city', 'destination_city'], name='flights_fli_departu_909158_idx'), models.Index(fields=['departure_date', 'status'], name='flights_fli_departu_d92af0_idx'), models.Index(fields=['price'], name='flights_fli_price_59fecb_idx')],
            },
        ),
    ]
