from django.core.management.base import BaseCommand

from packages.models import TravelPackage


class Command(BaseCommand):
    help = 'Seed sample holiday packages'

    def handle(self, *args, **kwargs):
        data = [
            {
                "title": "Swiss Alps Adventure",
                "destination": "Interlaken",
                "country": "Switzerland",
                "state": "Bernese Oberland",
                "duration_days": 7,
                "duration_nights": 6,
                "category": "Adventure",
                "description": "Experience the thrill of the Swiss Alps with paragliding, hiking, and cable car rides. Stay in a charming chalet with panoramic mountain views. This package includes guided treks through lush green valleys, visits to pristine alpine lakes, and an unforgettable Jungfraujoch excursion.",
                "price": 1899.00,
                "discount_percentage": 15,
                "max_travelers": 16,
                "difficulty_level": "Moderate",
                "best_travel_season": "May–September",
                "inclusions": ["6 nights hotel accommodation", "Daily breakfast & dinner", "Airport transfers", "English-speaking guide", "Paragliding session", "Jungfraujoch railway ticket", "Travel insurance"],
                "exclusions": ["International flights", "Lunch & beverages", "Personal expenses", "Visa fees"],
                "highlights": ["Paragliding over Interlaken", "Jungfraujoch – Top of Europe", "Lake Brienz cruise", "Grindelwald hiking trails", "Swiss chocolate tasting"],
                "average_rating": 4.8,
                "total_reviews": 124,
                "featured": True,
                "active": True,
            },
            {
                "title": "Maldives Honeymoon Escape",
                "destination": "Male",
                "country": "Maldives",
                "state": "South Male Atoll",
                "duration_days": 5,
                "duration_nights": 4,
                "category": "Honeymoon",
                "description": "A romantic getaway in overwater villas with private pools, sunset cruises, and candlelit dinners on the beach. Perfect for couples seeking privacy and luxury in paradise. Snorkel among vibrant coral reefs and relax with world-class spa treatments.",
                "price": 2499.00,
                "discount_percentage": 10,
                "max_travelers": 2,
                "difficulty_level": "Easy",
                "best_travel_season": "November–April",
                "inclusions": ["4 nights overwater villa", "Private pool", "All-inclusive meals", "Sunset cruise", "Couples spa session", "Snorkeling gear", "Speedboat transfers"],
                "exclusions": ["International flights", "Premium beverages", "Scuba diving courses", "Tips"],
                "highlights": ["Overwater villa with glass floor", "Private sunset dinner on sandbank", "Manta ray snorkeling", "Underwater restaurant experience", "Couples Ayurvedic massage"],
                "average_rating": 4.9,
                "total_reviews": 87,
                "featured": True,
                "active": True,
            },
            {
                "title": "Rajasthan Royal Heritage Tour",
                "destination": "Jaipur",
                "country": "India",
                "state": "Rajasthan",
                "duration_days": 10,
                "duration_nights": 9,
                "category": "Luxury",
                "description": "Explore the majestic forts, palaces, and vibrant bazaars of Rajasthan. Travel in style with heritage hotel stays, private car transfers, and expert guides. Visit Jaipur's Hawa Mahal, Udaipur's Lake Palace, Jodhpur's Mehrangarh Fort, and Jaisalmer's golden dunes.",
                "price": 1499.00,
                "discount_percentage": 20,
                "max_travelers": 20,
                "difficulty_level": "Easy",
                "best_travel_season": "October–March",
                "inclusions": ["9 nights heritage hotel stay", "Daily breakfast", "Private AC vehicle", "Professional guide", "Elephant ride at Amber Fort", "Camel safari in Jaisalmer", "Folk dance performance"],
                "exclusions": ["Flights", "Lunch & dinner", "Monument entry fees", "Camera charges", "Tips"],
                "highlights": ["Amber Fort elephant ride", "Lake Pichola boat cruise", "Mehrangarh Fort zip line", "Desert camping under stars", "Block printing workshop"],
                "average_rating": 4.6,
                "total_reviews": 203,
                "featured": True,
                "active": True,
            },
            {
                "title": "Thailand Family Fun Package",
                "destination": "Bangkok",
                "country": "Thailand",
                "state": "",
                "duration_days": 8,
                "duration_nights": 7,
                "category": "Family",
                "description": "A perfect family vacation combining Bangkok's vibrant culture, Phuket's stunning beaches, and Khao Sok's wildlife. Kid-friendly activities include elephant sanctuaries, water parks, and cooking classes suitable for all ages.",
                "price": 899.00,
                "discount_percentage": 0,
                "max_travelers": 4,
                "difficulty_level": "Easy",
                "best_travel_season": "November–February",
                "inclusions": ["7 nights 4-star accommodation", "Daily breakfast", "Domestic flights Bangkok–Phuket", "Elephant sanctuary visit", "Phi Phi Island day trip", "Thai cooking class", "All transfers"],
                "exclusions": ["International flights", "Lunch & dinner", "Visa on arrival", "Personal expenses", "Travel insurance"],
                "highlights": ["Grand Palace & Wat Pho tour", "Elephant sanctuary experience", "Phi Phi Island snorkeling", "Floating market visit", "Night market food crawl"],
                "average_rating": 4.5,
                "total_reviews": 312,
                "featured": False,
                "active": True,
            },
            {
                "title": "Bali Fitness & Wellness Retreat",
                "destination": "Ubud",
                "country": "Indonesia",
                "state": "Bali",
                "duration_days": 6,
                "duration_nights": 5,
                "category": "Solo",
                "description": "Rejuvenate your mind and body in the lush jungles of Ubud. Daily yoga sessions, meditation workshops, organic farm-to-table meals, and spa treatments. This solo-friendly retreat includes group activities and plenty of personal time.",
                "price": 699.00,
                "discount_percentage": 5,
                "max_travelers": 12,
                "difficulty_level": "Easy",
                "best_travel_season": "April–October",
                "inclusions": ["5 nights eco-resort stay", "Daily yoga & meditation", "All organic meals", "2 spa treatments", "Rice terrace trek", "Airport pickup", "Welcome kit"],
                "exclusions": ["Flights", "Additional spa services", "Shopping expenses", "Laundry"],
                "highlights": ["Sunrise yoga at Tegallalang", "Sacred Monkey Forest visit", "Tirta Empul water temple", "Bali swing experience", "Silver jewelry making class"],
                "average_rating": 4.7,
                "total_reviews": 98,
                "featured": False,
                "active": True,
            },
            {
                "title": "Kenya Wildlife Safari",
                "destination": "Nairobi",
                "country": "Kenya",
                "state": "",
                "duration_days": 9,
                "duration_nights": 8,
                "category": "Wildlife",
                "description": "Embark on an unforgettable African safari across Masai Mara, Amboseli, and Tsavo. Witness the Big Five, the Great Migration, and breathtaking savanna sunsets. Stay in luxury tented camps with expert ranger guides.",
                "price": 3299.00,
                "discount_percentage": 12,
                "max_travelers": 10,
                "difficulty_level": "Moderate",
                "best_travel_season": "July–October",
                "inclusions": ["8 nights luxury tented camp", "Full board meals", "4×4 safari vehicle", "Professional ranger guide", "Park entry fees", "Nairobi airport transfers", "Bush dinner experience"],
                "exclusions": ["International flights", "Visa fees", "Vaccinations", "Travel insurance", "Tips"],
                "highlights": ["Masai Mara Big Five safari", "Great Migration river crossing", "Amboseli elephants with Kilimanjaro", "Masai village cultural visit", "Hot air balloon safari"],
                "average_rating": 4.9,
                "total_reviews": 156,
                "featured": True,
                "active": True,
            },
            {
                "title": "Goa Beachside Vacation",
                "destination": "Goa",
                "country": "India",
                "state": "Goa",
                "duration_days": 5,
                "duration_nights": 4,
                "category": "Beach",
                "description": "Unwind on Goa's pristine beaches with this relaxed vacation package. Enjoy water sports, beach shacks, Portuguese heritage walks, and vibrant nightlife. Perfect for both relaxation and adventure seekers.",
                "price": 399.00,
                "discount_percentage": 0,
                "max_travelers": 6,
                "difficulty_level": "Easy",
                "best_travel_season": "November–March",
                "inclusions": ["4 nights beach resort stay", "Daily breakfast", "Airport transfers", "Sunset cruise", "Water sports (banana boat, jet ski)", "North & South Goa sightseeing", "One candlelight dinner"],
                "exclusions": ["Flights", "Lunch & other meals", "Alcohol", "Personal expenses"],
                "highlights": ["Baga & Anjuna beach hopping", "Fort Aguada visit", "Dudhsagar Falls trek", "Spice plantation tour", "Goan seafood feast"],
                "average_rating": 4.3,
                "total_reviews": 445,
                "featured": False,
                "active": True,
            },
            {
                "title": "Manali Snow Adventure",
                "destination": "Manali",
                "country": "India",
                "state": "Himachal Pradesh",
                "duration_days": 6,
                "duration_nights": 5,
                "category": "Hill Station",
                "description": "Escape to the snow-capped peaks of Manali. Enjoy skiing, snowboarding, and cozy bonfires by the river. This package also includes a visit to Solang Valley, Rohtang Pass, and ancient Hadimba Temple.",
                "price": 549.00,
                "discount_percentage": 10,
                "max_travelers": 15,
                "difficulty_level": "Moderate",
                "best_travel_season": "December–February",
                "inclusions": ["5 nights hotel stay", "Daily meals", "Skiing equipment & instructor", "Solang Valley visit", "Rohtang Pass permit & transport", "Bonfire night", "Volvo bus transfer from Delhi"],
                "exclusions": ["Flights", "Personal gear", "Hot springs entry", "Tips"],
                "highlights": ["Solang Valley skiing", "Rohtang Pass snow adventure", "Old Manali cafe hopping", "Hadimba Temple visit", "River rafting in Kullu"],
                "average_rating": 4.4,
                "total_reviews": 278,
                "featured": False,
                "active": True,
            },
            {
                "title": "Greece Island Hopping",
                "destination": "Athens",
                "country": "Greece",
                "state": "",
                "duration_days": 12,
                "duration_nights": 11,
                "category": "Group",
                "description": "Island-hop across the stunning Greek Isles — Santorini, Mykonos, and Crete. Explore ancient ruins, whitewashed villages, crystal-clear waters, and vibrant nightlife. Ideal for groups of friends or couples.",
                "price": 2199.00,
                "discount_percentage": 18,
                "max_travelers": 12,
                "difficulty_level": "Easy",
                "best_travel_season": "May–September",
                "inclusions": ["11 nights hotel & villa stays", "Domestic ferry tickets", "Daily breakfast", "Athens city tour", "Santorini sunset cruise", "Mykonos beach club entry", "Cooking class in Crete"],
                "exclusions": ["International flights", "Lunch & dinner", "Museum entry fees", "Tips"],
                "highlights": ["Santorini sunset in Oia", "Mykonos windmills & Little Venice", "Knossos Palace in Crete", "Athens Acropolis & Parthenon", "Blue Lagoon swimming"],
                "average_rating": 4.7,
                "total_reviews": 189,
                "featured": True,
                "active": True,
            },
            {
                "title": "Dubai Luxury Experience",
                "destination": "Dubai",
                "country": "UAE",
                "state": "",
                "duration_days": 5,
                "duration_nights": 4,
                "category": "Luxury",
                "description": "Live the high life in Dubai with 5-star hotel stays, desert safaris, Burj Khalifa views, and world-class shopping. Includes VIP access to top attractions and fine dining experiences.",
                "price": 1799.00,
                "discount_percentage": 0,
                "max_travelers": 8,
                "difficulty_level": "Easy",
                "best_travel_season": "November–March",
                "inclusions": ["4 nights 5-star hotel", "Daily breakfast", "Desert safari with BBQ dinner", "Burj Khalifa At The Top VIP", "Dubai Marina yacht tour", "Airport transfers in luxury car", "Dubai Mall shopping voucher"],
                "exclusions": ["Flights", "Lunch & dinner", "Visa fees", "Personal shopping"],
                "highlights": ["Burj Khalifa observation deck", "Desert dune bashing", "Palm Jumeirah skydive view", "Gold & spice souk tour", "Dubai Fountain show"],
                "average_rating": 4.6,
                "total_reviews": 234,
                "featured": False,
                "active": True,
            },
            {
                "title": "Kerala Backwaters & Ayurveda",
                "destination": "Kumarakom",
                "country": "India",
                "state": "Kerala",
                "duration_days": 7,
                "duration_nights": 6,
                "category": "Wellness",
                "description": "Detox and rejuvenate on a traditional Kerala houseboat cruise through serene backwaters. Includes Ayurvedic treatments, yoga sessions, and farm-fresh Kerala cuisine. A perfect wellness escape.",
                "price": 649.00,
                "discount_percentage": 15,
                "max_travelers": 10,
                "difficulty_level": "Easy",
                "best_travel_season": "September–March",
                "inclusions": ["3 nights houseboat, 3 nights resort", "All meals on houseboat", "Ayurvedic massage (3 sessions)", "Daily yoga", "Village canoe ride", "Kathakali dance performance", "Cochin city tour"],
                "exclusions": ["Flights", "Additional treatments", "Tips", "Shopping"],
                "highlights": ["Houseboat cruise on Vembanad Lake", "Sunset bird watching", "Traditional Kerala sadya meal", "Spice garden visit", "Elephant bath experience"],
                "average_rating": 4.5,
                "total_reviews": 167,
                "featured": False,
                "active": True,
            },
            {
                "title": "Vietnam Backpacker Trail",
                "destination": "Hanoi",
                "country": "Vietnam",
                "state": "",
                "duration_days": 14,
                "duration_nights": 13,
                "category": "Solo",
                "description": "The ultimate Vietnam adventure from Hanoi to Ho Chi Minh City. Cruise Ha Long Bay, explore ancient Hoi An, trek Sapa rice terraces, and discover Mekong Delta floating markets. Budget-friendly hostels with social activities.",
                "price": 599.00,
                "discount_percentage": 0,
                "max_travelers": 20,
                "difficulty_level": "Moderate",
                "best_travel_season": "October–April",
                "inclusions": ["13 nights hostel & hotel stay", "Ha Long Bay 2-day cruise", "Overnight train to Hoi An", "Mekong Delta boat tour", "Cu Chi tunnels tour", "English-speaking guide", "Domestic flights Ho Chi Minh–Hanoi"],
                "exclusions": ["International flights", "Meals (except on cruise)", "Visa", "Personal expenses"],
                "highlights": ["Ha Long Bay kayaking", "Hoi An lantern festival", "Sapa rice terrace trekking", "Mekong floating market", "Vietnamese street food tour"],
                "average_rating": 4.4,
                "total_reviews": 356,
                "featured": False,
                "active": True,
            },
            {
                "title": "Iceland Northern Lights Chase",
                "destination": "Reykjavik",
                "country": "Iceland",
                "state": "",
                "duration_days": 6,
                "duration_nights": 5,
                "category": "Adventure",
                "description": "Chase the aurora borealis across Iceland's otherworldly landscapes. Visit geysers, waterfalls, glaciers, and black sand beaches. Includes guided northern lights hunting with photography tips.",
                "price": 2199.00,
                "discount_percentage": 10,
                "max_travelers": 12,
                "difficulty_level": "Moderate",
                "best_travel_season": "October–March",
                "inclusions": ["5 nights hotel & cabin stays", "Daily breakfast", "4WD vehicle rental", "Northern lights guide", "Blue Lagoon entry", "Glacier hiking gear", "Airport transfers"],
                "exclusions": ["International flights", "Fuel costs", "Lunch & dinner", "Travel insurance", "Thermal clothing rental"],
                "highlights": ["Northern lights photography", "Golden Circle tour", "Jökulsárlón glacier lagoon", "Seljalandsfoss waterfall", "Blue Lagoon geothermal spa"],
                "average_rating": 4.8,
                "total_reviews": 143,
                "featured": True,
                "active": True,
            },
            {
                "title": "Andaman Island Escape",
                "destination": "Port Blair",
                "country": "India",
                "state": "Andaman & Nicobar",
                "duration_days": 6,
                "duration_nights": 5,
                "category": "Beach",
                "description": "Discover India's hidden paradise — the Andaman Islands. Crystal clear waters, pristine beaches, coral reefs, and historic cellular jail. Includes snorkeling at Havelock Island and a visit to Radhanagar Beach, Asia's best beach.",
                "price": 499.00,
                "discount_percentage": 0,
                "max_travelers": 15,
                "difficulty_level": "Easy",
                "best_travel_season": "November–May",
                "inclusions": ["5 nights beach resort stay", "Daily breakfast & dinner", "Ferry to Havelock & Neil Island", "Snorkeling gear", "Cellular Jail light & sound show", "All transfers", "Glass-bottom boat ride"],
                "exclusions": ["Flights to Port Blair", "Lunch", "Scuba diving", "Personal expenses"],
                "highlights": ["Radhanagar Beach sunset", "Elephanta Beach snorkeling", "Neil Island cycling tour", "Cellular Jail history tour", "Baratang limestone caves"],
                "average_rating": 4.5,
                "total_reviews": 198,
                "featured": False,
                "active": True,
            },
            {
                "title": "Japan Cherry Blossom Tour",
                "destination": "Tokyo",
                "country": "Japan",
                "state": "",
                "duration_days": 10,
                "duration_nights": 9,
                "category": "Group",
                "description": "Witness Japan's iconic cherry blossom season across Tokyo, Kyoto, and Osaka. Bullet train rides, traditional tea ceremonies, samurai shows, and a stay in a ryokan. A cultural feast for the senses.",
                "price": 2899.00,
                "discount_percentage": 5,
                "max_travelers": 16,
                "difficulty_level": "Easy",
                "best_travel_season": "Late March–Early April",
                "inclusions": ["9 nights hotel & ryokan stay", "Daily breakfast", "7-day JR Rail Pass", "Tea ceremony experience", "Mt. Fuji day trip", "Osaka street food tour", "English-speaking guide"],
                "exclusions": ["International flights", "Lunch & dinner", "Visa fees", "Personal shopping"],
                "highlights": ["Senso-ji Temple & Asakusa", "Fushimi Inari shrine walk", "Arashiyama bamboo grove", "Osaka Dotonbori nightlife", "Shinkansen bullet train ride"],
                "average_rating": 4.8,
                "total_reviews": 212,
                "featured": True,
                "active": True,
            },
            {
                "title": "Ladakh Bike Expedition",
                "destination": "Leh",
                "country": "India",
                "state": "Ladakh",
                "duration_days": 12,
                "duration_nights": 11,
                "category": "Adventure",
                "description": "Conquer the highest motorable passes in the world on a Royal Enfield expedition through Ladakh. Ride through Khardung La, Nubra Valley, Pangong Tso, and Tso Moriri. A bucket-list adventure for bikers.",
                "price": 899.00,
                "discount_percentage": 0,
                "max_travelers": 10,
                "difficulty_level": "Hard",
                "best_travel_season": "June–September",
                "inclusions": ["11 nights camp & guesthouse stay", "Royal Enfield 350cc rental", "Fuel for entire trip", "Mechanical support vehicle", "All meals", "Inner line permits", "Expert tour leader"],
                "exclusions": ["Flights to Leh", "Gear rental (helmet, jacket)", "Personal expenses", "Tips"],
                "highlights": ["Khardung La Pass (18,380 ft)", "Pangong Tso lake camping", "Nubra Valley sand dunes", "Tso Moriri bird sanctuary", "Magnetic Hill & Sangam"],
                "average_rating": 4.9,
                "total_reviews": 88,
                "featured": False,
                "active": True,
            },
            {
                "title": "Santorini Sunset Honeymoon",
                "destination": "Santorini",
                "country": "Greece",
                "state": "",
                "duration_days": 5,
                "duration_nights": 4,
                "category": "Honeymoon",
                "description": "The most romantic Greek island experience. Stay in a cave suite with a private infinity pool overlooking the caldera. Enjoy wine tasting, a catamaran cruise, and the most famous sunsets in the world.",
                "price": 1999.00,
                "discount_percentage": 0,
                "max_travelers": 2,
                "difficulty_level": "Easy",
                "best_travel_season": "April–October",
                "inclusions": ["4 nights caldera-view cave suite", "Private infinity pool", "Daily breakfast", "Catamaran cruise with dinner", "Wine tasting tour", "Private airport transfer", "Couples photoshoot"],
                "exclusions": ["Flights", "Lunch & dinner (except cruise)", "Personal expenses"],
                "highlights": ["Oia sunset viewing", "Caldera catamaran cruise", "Red Beach & White Beach", "Akrotiri ancient ruins", "Wine tasting at Santo Wines"],
                "average_rating": 4.9,
                "total_reviews": 67,
                "featured": False,
                "active": True,
            },
            {
                "title": "Costa Rica Eco Adventure",
                "destination": "San José",
                "country": "Costa Rica",
                "state": "",
                "duration_days": 10,
                "duration_nights": 9,
                "category": "Wildlife",
                "description": "Explore Costa Rica's incredible biodiversity — rainforests, volcanoes, cloud forests, and Pacific beaches. Zip-line through the canopy, spot sloths and toucans, and relax in natural hot springs.",
                "price": 1799.00,
                "discount_percentage": 8,
                "max_travelers": 14,
                "difficulty_level": "Moderate",
                "best_travel_season": "December–April",
                "inclusions": ["9 nights eco-lodge stays", "Daily breakfast", "Zip-lining & canopy tour", "Arenal Volcano hot springs", "Monteverde cloud forest hike", "Manual Antonio beach day", "All transfers"],
                "exclusions": ["International flights", "Lunch & dinner", "Travel insurance", "Tips"],
                "highlights": ["Arenal Volcano night hike", "Monteverde hanging bridges", "Sloth sanctuary visit", "White-water rafting", "Coffee plantation tour"],
                "average_rating": 4.7,
                "total_reviews": 129,
                "featured": False,
                "active": True,
            },
            {
                "title": "Egypt Pyramids & Nile Cruise",
                "destination": "Cairo",
                "country": "Egypt",
                "state": "",
                "duration_days": 8,
                "duration_nights": 7,
                "category": "Group",
                "description": "Step back in time with a journey through ancient Egypt. Visit the Pyramids of Giza, Sphinx, Valley of the Kings, and cruise the Nile from Luxor to Aswan. Includes expert Egyptologist guides.",
                "price": 1399.00,
                "discount_percentage": 0,
                "max_travelers": 20,
                "difficulty_level": "Easy",
                "best_travel_season": "October–April",
                "inclusions": ["7 nights hotel & Nile cruise", "Daily breakfast", "Egyptologist guide", "Pyramids & Sphinx visit", "Nile cruise Luxor–Aswan", "Karnak Temple & Valley of the Kings", "Airport transfers"],
                "exclusions": ["International flights", "Visa", "Lunch & dinner", "Entry inside pyramids", "Tips"],
                "highlights": ["Pyramids of Giza & Sphinx", "Luxor Temple at night", "Karnak sound & light show", "Abu Simbel day trip", "Nile felucca sunset ride"],
                "average_rating": 4.5,
                "total_reviews": 276,
                "featured": False,
                "active": True,
            },
            {
                "title": "Scottish Highlands & Whisky Trail",
                "destination": "Edinburgh",
                "country": "United Kingdom",
                "state": "Scotland",
                "duration_days": 7,
                "duration_nights": 6,
                "category": "Solo",
                "description": "Journey through the misty Scottish Highlands, ancient castles, and world-famous whisky distilleries. Hike the Isle of Skye, explore Loch Ness, and sample drams at Speyside distilleries. Solo-friendly group tour.",
                "price": 1599.00,
                "discount_percentage": 0,
                "max_travelers": 14,
                "difficulty_level": "Moderate",
                "best_travel_season": "May–September",
                "inclusions": ["6 nights B&B & castle hotel stays", "Daily breakfast", "Transport in minibus", "Scottish guide", "Distillery tour & tasting (3)", "Isle of Skye ferry", "Edinburgh Castle entry"],
                "exclusions": ["Flights", "Lunch & dinner", "Personal expenses"],
                "highlights": ["Edinburgh Castle & Royal Mile", "Loch Ness boat tour", "Isle of Skye Fairy Pools", "Glenfiddich distillery tour", "Jacobite steam train ride"],
                "average_rating": 4.6,
                "total_reviews": 112,
                "featured": False,
                "active": True,
            },
        ]

        created = 0
        for item in data:
            pkg, was_created = TravelPackage.objects.get_or_create(
                title=item["title"],
                defaults=item,
            )
            if was_created:
                created += 1
                self.stdout.write(self.style.SUCCESS(f'  [OK] {pkg.title}'))
            else:
                self.stdout.write(f'  – {pkg.title} (already exists)')

        total = TravelPackage.objects.count()
        self.stdout.write(self.style.SUCCESS(f'\nDone. {created} new packages added. Total: {total}'))
