from datetime import time

from django.core.management.base import BaseCommand

from hotels.models import Hotel


class Command(BaseCommand):
    help = 'Seed the database with sample hotel data'

    def handle(self, *args, **kwargs):
        hotels_data = [
            {
                'name': 'Grand Horizon Resort & Spa',
                'city': 'Miami',
                'state': 'Florida',
                'country': 'United States',
                'address': '1200 Ocean Drive, Miami Beach, FL 33139',
                'description': 'Experience unparalleled luxury at the Grand Horizon Resort & Spa. Nestled along the pristine beaches of Miami, our resort offers breathtaking ocean views, world-class dining, and a rejuvenating spa experience. Each room is meticulously designed with modern elegance and equipped with premium amenities to ensure an unforgettable stay.',
                'star_rating': 5,
                'average_rating': 4.8,
                'price_per_night': 450.00,
                'discount_percentage': 20,
                'total_rooms': 200,
                'available_rooms': 45,
                'check_in_time': time(15, 0),
                'check_out_time': time(11, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': True,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': 25.7617,
                'longitude': -80.1918,
                'contact_email': 'reservations@grandhorizon.com',
                'contact_phone': '+1-305-555-0100',
                'website': 'https://grandhorizon.example.com',
                'featured': True,
                'active': True,
            },
            {
                'name': 'The Skyline Boutique Hotel',
                'city': 'New York',
                'state': 'New York',
                'country': 'United States',
                'address': '350 Fifth Avenue, New York, NY 10118',
                'description': 'The Skyline Boutique Hotel offers a sophisticated urban retreat in the heart of Manhattan. Steps from iconic landmarks, our hotel combines contemporary design with personalized service. Enjoy panoramic city views from our rooftop bar, indulge in farm-to-table cuisine, and relax in elegantly appointed rooms.',
                'star_rating': 4,
                'average_rating': 4.5,
                'price_per_night': 320.00,
                'discount_percentage': 0,
                'total_rooms': 150,
                'available_rooms': 78,
                'check_in_time': time(15, 0),
                'check_out_time': time(12, 0),
                'wifi': True,
                'pool': False,
                'parking': False,
                'spa': False,
                'gym': True,
                'restaurant': True,
                'ac': True,
                'breakfast': False,
                'pet_friendly': True,
                'latitude': 40.7484,
                'longitude': -73.9857,
                'contact_email': 'hello@skylineboutique.com',
                'contact_phone': '+1-212-555-0200',
                'website': 'https://skylineboutique.example.com',
                'featured': True,
                'active': True,
            },
            {
                'name': 'Casa del Sol Beach Resort',
                'city': 'Cancun',
                'state': 'Quintana Roo',
                'country': 'Mexico',
                'address': 'Boulevard Kukulcan Km 9.5, Cancun, QROO 77500',
                'description': 'Casa del Sol Beach Resort is a tropical paradise on the shores of the Caribbean. With crystal-clear waters, white sandy beaches, and lush tropical gardens, our all-inclusive resort offers the ultimate getaway. Enjoy unlimited cocktails, water sports, and nightly entertainment.',
                'star_rating': 4,
                'average_rating': 4.3,
                'price_per_night': 220.00,
                'discount_percentage': 15,
                'total_rooms': 300,
                'available_rooms': 120,
                'check_in_time': time(15, 0),
                'check_out_time': time(12, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': True,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': 21.1619,
                'longitude': -86.8515,
                'contact_email': 'info@casadelsool.com',
                'contact_phone': '+52-998-555-0300',
                'website': 'https://casadelsool.example.com',
                'featured': True,
                'active': True,
            },
            {
                'name': 'Alpine Lodge & Chalets',
                'city': 'Zurich',
                'state': 'Zurich',
                'country': 'Switzerland',
                'address': 'Bahnhofstrasse 100, 8001 Zurich',
                'description': 'Alpine Lodge & Chalets offers a cozy mountain retreat with stunning views of the Swiss Alps. Our wood-paneled chalets combine traditional charm with modern luxury. Enjoy world-class skiing in winter, hiking in summer, and exceptional fondue year-round.',
                'star_rating': 4,
                'average_rating': 4.7,
                'price_per_night': 380.00,
                'discount_percentage': 10,
                'total_rooms': 80,
                'available_rooms': 22,
                'check_in_time': time(14, 0),
                'check_out_time': time(10, 0),
                'wifi': True,
                'pool': False,
                'parking': True,
                'spa': True,
                'gym': False,
                'restaurant': True,
                'ac': False,
                'breakfast': True,
                'pet_friendly': True,
                'latitude': 47.3769,
                'longitude': 8.5417,
                'contact_email': 'stay@alpinelodge.ch',
                'contact_phone': '+41-44-555-0400',
                'website': 'https://alpinelodge.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'Sakura Inn Tokyo',
                'city': 'Tokyo',
                'state': 'Tokyo',
                'country': 'Japan',
                'address': '2-3-4 Shibuya, Shibuya City, Tokyo 150-0002',
                'description': 'Sakura Inn Tokyo blends traditional Japanese hospitality with modern comfort. Located in the vibrant Shibuya district, our inn offers authentic tatami rooms, a serene garden, and a relaxing onsen. Experience the beauty of Japan with our guided cultural activities.',
                'star_rating': 3,
                'average_rating': 4.2,
                'price_per_night': 180.00,
                'discount_percentage': 0,
                'total_rooms': 60,
                'available_rooms': 15,
                'check_in_time': time(15, 0),
                'check_out_time': time(10, 0),
                'wifi': True,
                'pool': False,
                'parking': False,
                'spa': True,
                'gym': False,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': 35.6580,
                'longitude': 139.7016,
                'contact_email': 'info@sakurainn.jp',
                'contact_phone': '+81-3-5555-0500',
                'website': 'https://sakurainn.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'The Ritz Grand Paris',
                'city': 'Paris',
                'state': 'Ile-de-France',
                'country': 'France',
                'address': '15 Place Vendôme, 75001 Paris',
                'description': 'The Ritz Grand Paris epitomizes French luxury and refinement. Overlooking the iconic Place Vendôme, our palace hotel offers opulent suites, a Michelin-starred restaurant, and a world-class spa. Every detail reflects the artistry and elegance of Parisian haute couture.',
                'star_rating': 5,
                'average_rating': 4.9,
                'price_per_night': 950.00,
                'discount_percentage': 25,
                'total_rooms': 120,
                'available_rooms': 12,
                'check_in_time': time(15, 0),
                'check_out_time': time(12, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': True,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': True,
                'latitude': 48.8683,
                'longitude': 2.3290,
                'contact_email': 'concierge@ritzgrandparis.com',
                'contact_phone': '+33-1-5555-0600',
                'website': 'https://ritzgrandparis.example.com',
                'featured': True,
                'active': True,
            },
            {
                'name': 'Desert Oasis Camp',
                'city': 'Dubai',
                'state': 'Dubai',
                'country': 'United Arab Emirates',
                'address': 'Al Qudra Road, Dubai Desert Conservation Reserve',
                'description': 'Desert Oasis Camp offers a unique luxury glamping experience in the Arabian desert. Sleep under the stars in a lavish Bedouin-style tent, enjoy camel treks at sunset, and feast under the desert sky. An unforgettable escape from the modern world.',
                'star_rating': 5,
                'average_rating': 4.6,
                'price_per_night': 650.00,
                'discount_percentage': 0,
                'total_rooms': 30,
                'available_rooms': 8,
                'check_in_time': time(14, 0),
                'check_out_time': time(11, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': False,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': 24.7136,
                'longitude': 55.1673,
                'contact_email': 'stay@desertoasis.ae',
                'contact_phone': '+971-4-555-0700',
                'website': 'https://desertoasis.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'Harbor Lights Inn',
                'city': 'Sydney',
                'state': 'New South Wales',
                'country': 'Australia',
                'address': '1 Circular Quay, Sydney NSW 2000',
                'description': 'Harbor Lights Inn offers stunning views of the Sydney Opera House and Harbour Bridge. Our boutique hotel combines contemporary Australian design with warm hospitality. Enjoy fresh seafood at our waterfront restaurant and explore the vibrant Rocks district.',
                'star_rating': 4,
                'average_rating': 4.4,
                'price_per_night': 290.00,
                'discount_percentage': 12,
                'total_rooms': 90,
                'available_rooms': 35,
                'check_in_time': time(14, 0),
                'check_out_time': time(11, 0),
                'wifi': True,
                'pool': True,
                'parking': False,
                'spa': False,
                'gym': True,
                'restaurant': True,
                'ac': True,
                'breakfast': False,
                'pet_friendly': True,
                'latitude': -33.8568,
                'longitude': 151.2153,
                'contact_email': 'info@harborlights.com.au',
                'contact_phone': '+61-2-5555-0800',
                'website': 'https://harborlights.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'Royal Heritage Palace',
                'city': 'Jaipur',
                'state': 'Rajasthan',
                'country': 'India',
                'address': 'Amer Road, Jaipur, Rajasthan 302001',
                'description': 'Royal Heritage Palace offers a majestic stay in a restored 18th-century palace. Surrounded by the rugged Aravalli hills, our palace hotel features intricate architecture, lush courtyards, and a tranquil Ayurvedic spa. Experience the grandeur of Rajasthan royalty.',
                'star_rating': 5,
                'average_rating': 4.7,
                'price_per_night': 280.00,
                'discount_percentage': 30,
                'total_rooms': 50,
                'available_rooms': 20,
                'check_in_time': time(14, 0),
                'check_out_time': time(11, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': False,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': 26.9852,
                'longitude': 75.8516,
                'contact_email': 'reservations@royalheritage.in',
                'contact_phone': '+91-141-555-0900',
                'website': 'https://royalheritage.example.com',
                'featured': True,
                'active': True,
            },
            {
                'name': 'Nordic Fjord Cabins',
                'city': 'Bergen',
                'state': 'Vestland',
                'country': 'Norway',
                'address': 'Fjordveien 42, 5003 Bergen',
                'description': 'Nordic Fjord Cabins offers a serene escape in the heart of the Norwegian fjords. Our minimalist glass cabins provide panoramic views of cascading waterfalls and towering cliffs. Enjoy northern lights viewing, fjord cruises, and hygge-inspired interiors.',
                'star_rating': 4,
                'average_rating': 4.8,
                'price_per_night': 350.00,
                'discount_percentage': 0,
                'total_rooms': 20,
                'available_rooms': 6,
                'check_in_time': time(15, 0),
                'check_out_time': time(12, 0),
                'wifi': True,
                'pool': False,
                'parking': True,
                'spa': False,
                'gym': False,
                'restaurant': True,
                'ac': False,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': 60.3913,
                'longitude': 5.3221,
                'contact_email': 'hello@nordicfjord.no',
                'contact_phone': '+47-55-555-1000',
                'website': 'https://nordicfjord.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'Sunset Beach Villas',
                'city': 'Bali',
                'state': 'Bali',
                'country': 'Indonesia',
                'address': 'Jl. Tanah Lot No. 1, Beraban, Tabanan, Bali 82171',
                'description': 'Sunset Beach Villas offers private pool villas overlooking the Indian Ocean. Each villa features traditional Balinese architecture with modern amenities, a private infinity pool, and an open-air living area. Experience the magic of Bali with our curated cultural experiences.',
                'star_rating': 5,
                'average_rating': 4.9,
                'price_per_night': 520.00,
                'discount_percentage': 18,
                'total_rooms': 25,
                'available_rooms': 10,
                'check_in_time': time(14, 0),
                'check_out_time': time(12, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': True,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': -8.6181,
                'longitude': 115.0885,
                'contact_email': 'villas@sunsetbeachbali.com',
                'contact_phone': '+62-361-555-1100',
                'website': 'https://sunsetbeachbali.example.com',
                'featured': True,
                'active': True,
            },
            {
                'name': 'CityZen Budget Hotel',
                'city': 'Bangkok',
                'state': 'Bangkok',
                'country': 'Thailand',
                'address': '123 Sukhumvit Road, Khlong Toei, Bangkok 10110',
                'description': 'CityZen Budget Hotel offers clean, comfortable accommodations at affordable prices. Located in the heart of Sukhumvit, our hotel provides easy access to Bangkok\'s best shopping, dining, and nightlife. Perfect for budget-conscious travelers who don\'t want to compromise on quality.',
                'star_rating': 2,
                'average_rating': 3.8,
                'price_per_night': 55.00,
                'discount_percentage': 0,
                'total_rooms': 80,
                'available_rooms': 40,
                'check_in_time': time(14, 0),
                'check_out_time': time(12, 0),
                'wifi': True,
                'pool': False,
                'parking': False,
                'spa': False,
                'gym': False,
                'restaurant': False,
                'ac': True,
                'breakfast': False,
                'pet_friendly': False,
                'latitude': 13.7367,
                'longitude': 100.5604,
                'contact_email': 'stay@cityzenbkk.com',
                'contact_phone': '+66-2-555-1200',
                'website': 'https://cityzenbkk.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'Vineyard Estate & Cottages',
                'city': 'Tuscany',
                'state': 'Tuscany',
                'country': 'Italy',
                'address': 'Via delle Vigne 25, 53024 Montalcino SI',
                'description': 'Vineyard Estate & Cottages offers a romantic Italian countryside experience. Set among rolling hills of grapevines and olive groves, our estate features rustic-chic cottages, a farm-to-table restaurant, and wine tastings in our historic cellar. The perfect Tuscan retreat.',
                'star_rating': 4,
                'average_rating': 4.6,
                'price_per_night': 310.00,
                'discount_percentage': 8,
                'total_rooms': 15,
                'available_rooms': 7,
                'check_in_time': time(14, 0),
                'check_out_time': time(10, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': False,
                'gym': False,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': True,
                'latitude': 43.0587,
                'longitude': 11.4892,
                'contact_email': 'info@vineyardestate.it',
                'contact_phone': '+39-0577-555-1300',
                'website': 'https://vineyardestate.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'Safari Lodge & Tented Camp',
                'city': 'Nairobi',
                'state': 'Nairobi',
                'country': 'Kenya',
                'address': 'Karen, Nairobi 00100',
                'description': 'Safari Lodge & Tented Camp offers an authentic African safari experience. Wake up to the sounds of wildlife, embark on game drives in search of the Big Five, and enjoy sundowners overlooking the savannah. Our luxury tents combine adventure with comfort.',
                'star_rating': 4,
                'average_rating': 4.7,
                'price_per_night': 420.00,
                'discount_percentage': 0,
                'total_rooms': 25,
                'available_rooms': 14,
                'check_in_time': time(12, 0),
                'check_out_time': time(10, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': False,
                'restaurant': True,
                'ac': False,
                'breakfast': True,
                'pet_friendly': False,
                'latitude': -1.3701,
                'longitude': 36.7503,
                'contact_email': 'safari@safarilodge.co.ke',
                'contact_phone': '+254-20-555-1400',
                'website': 'https://safarilodge.example.com',
                'featured': False,
                'active': True,
            },
            {
                'name': 'The Lighthouse Inn',
                'city': 'Cape Town',
                'state': 'Western Cape',
                'country': 'South Africa',
                'address': '1 Lighthouse Road, Cape Town 8001',
                'description': 'The Lighthouse Inn offers breathtaking views of Table Mountain and the Atlantic Ocean. Our boutique hotel combines Cape Dutch architecture with contemporary African design. Explore the vibrant V&A Waterfront, sample award-winning wines, and witness stunning sunsets.',
                'star_rating': 5,
                'average_rating': 4.8,
                'price_per_night': 380.00,
                'discount_percentage': 15,
                'total_rooms': 45,
                'available_rooms': 18,
                'check_in_time': time(14, 0),
                'check_out_time': time(11, 0),
                'wifi': True,
                'pool': True,
                'parking': True,
                'spa': True,
                'gym': True,
                'restaurant': True,
                'ac': True,
                'breakfast': True,
                'pet_friendly': True,
                'latitude': -33.9249,
                'longitude': 18.4241,
                'contact_email': 'info@lighthouseinn.co.za',
                'contact_phone': '+27-21-555-1500',
                'website': 'https://lighthouseinn.example.com',
                'featured': True,
                'active': True,
            },
        ]

        count = 0
        for data in hotels_data:
            _, created = Hotel.objects.get_or_create(
                name=data['name'],
                defaults=data
            )
            if created:
                count += 1

        self.stdout.write(
            self.style.SUCCESS(f'Successfully seeded {count} hotels ({len(hotels_data)} total in database)')
        )
